pretext: A clear path to help you “advance” in programming
title: SUTAP
description: Sharif University of Technology Advanced Programming course
university: Sharif University of Technology
course: Advanced Programming course
authors: Ahmad Salimi, Hamila Mailee

course_videos: 80+
course_duration: 72
course_lessons: 20
course_resources: 40+