pretext: Struct your Datas!
title: IUTDS
description: Isfahan University of Technology Data structure course
university: Isfahan University of Technology
course: Data structure course
authors: Dr.Samaneh Hoseini, Mohammad Mahdi Barghi

course_videos: 80+
course_duration: 72
course_lessons: 20
course_resources: 40+